/*
    Link: https://www.udemy.com/course/nodejs-the-complete-guide/learn/lecture/11561890#overview

    In the callback for the createServer you receive two implicit arguments, the request and the response
    objects. We will have a look at the request object.

    The request object holds information about the request generated by the user from the client.
    It contains details like the URL, headers, method name and a lot of other information.

    You can log the request object to see all the properties on it.

 */

